server:
  port: 8084
  # session-timeout: 1000000 #用户回话session过期时间，以秒为单位
  tomcat:
    uri-encoding: UTF-8 #配置Tomcat编码，默认为UTF-8
    compression: on #Tomcat是否开启压缩，默认为关闭
    disableUploadTimeout: false
    accesslog:
      directory: c:/pingan/log/
      enabled: true
      pattern: '%{ip}s %{userName}s %t "%r" %s %b %T'
      file-date-format: yyyy-MM-dd
      prefix: access_log.
      suffix: .log

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fundData?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: cm9vdA==
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
  mapper-locations: classpath:mybatis/mysql/*.xml
# 日志地址
logging:
  config: classpath:logback.xml
  file:
    path: /logs/

# http ip地址配置
system:
  http:
    fund:
      host: http://fund.eastmoney.com
      #所有基金公司名称列表代码
      fundCompany: /js/jjjz_gs.js
      #所有基金名称列表代码
      allFund: /js/fundcode_search.js
      #基金详细信息
      fundDetail: /pingzhongdata
      #基金详细信息
      fundRealTime: http://fundgz.1234567.com.cn/js/